### ISSUE TITLE
Read access violation

### ISSUE THREAD

**Issue by Guffti** [tobbep1997/RipTag#10]
StatichMesh.cpp

Destructor kraschar på att ta bort collisionboxes när: "Play game" -> "Esc" -> "Play game". 
Ger minesläcka om utkommenterat

**Comment by tobbep1997** [comment]
Git pull origin dev
Den är redan fixad

**Comment by TheFlyingPandaa** [comment]
Pullade senaste dev.
Fortfarande broken :c

**Comment by tobbep1997** [comment]
Ops 
NU är det fixat men minnesläckan kvarstår
#9
