### ISSUE TITLE
Shadow passet eller Shadow samplingen är buggad

### ISSUE THREAD

**Issue by nipplesticks** [tobbep1997/RipTag#26]
Vi har haft en liknande bugg tidigare.
Kanterna av shadowmapsen syns som rutor. plz fix

**Comment by tobbep1997** [comment]
Helvete

**Comment by tobbep1997** [comment]
![image](https://user-images.githubusercontent.com/10158150/48663787-662c3500-ea95-11e8-8cfd-e5ccd0bdacb7.png)
