### ISSUE TITLE
Vakter går inte efter smokebomb

### ISSUE THREAD

**Issue by TheFlyingPandaa** [tobbep1997/RipTag#30]
Guards får ingen path/Path dör wopwop
Den går inte helt enkelt vet inte varför

**Comment by TheFlyingPandaa** [comment]
Positionen verkar uppdatera men kroppen rör sig inte.
hmmmm 🤔

**Comment by TheFlyingPandaa** [comment]
Edit. De kommer aldrig till _moveTo()

**Comment by Vekzzor** [comment]
Har inget med disable att göra, vakten hör en till max av någon anledning vilket gör att den går aldrig tillbaka till patrol state för att den hittar en ny source att undersöka så fort den ska återgå till patrol.

**Comment by Vekzzor** [comment]
Hade med att torches var taggade som player ljud. funkar nu.
