### ISSUE TITLE
Optimera visibility 

### ISSUE THREAD

**Issue by TheFlyingPandaa** [tobbep1997/RipTag#4]

**Comment by TheFlyingPandaa** [comment]
Om vi kan plocka thread ID och skriva till flera uav slots så kan vi optimera lösningen

Dvs 
Output = thread.id % 10
Uav[output,0](lightCalc * 100);

**Comment by tobbep1997** [comment]
Vi kan också börja med om spelarens bounding box är i guard frustrum annars behöver det inte köras
