### ISSUE TITLE
Bounce random SpinLock

### ISSUE THREAD

**Issue by TheFlyingPandaa** [tobbep1997/RipTag#40]
SpinLock 4 ever

**Comment by tobbep1997** [comment]
I reduced the chance of it happening by 99%.

**Comment by TheFlyingPandaa** [comment]
DET KANSKE INTE ÄR BOUNCE

Rad 135
Grid.cpp
_getNearbyUnblockedTile(destination);

Det är här den stannar om man i release.
precis blir sed sen drar sig tillbaka.
🤔

**Comment by TheFlyingPandaa** [comment]
Den har inte spinat på länge, asså sjukt länge
I call closed. GJ bobby
