### ISSUE TITLE
Ljuset Cullas as wierd

### ISSUE THREAD

**Issue by nipplesticks** [tobbep1997/RipTag#63]
Är man framför ljust så cullas det.

**Comment by tobbep1997** [comment]
Är detta när man är en guard?

**Comment by nipplesticks** [comment]
Nej, som player

Den fre 7 dec. 2018 15:25 skrev Tobias Pogén <notifications@github.com>:

**Comment by tobbep1997** [comment]
Var det när en guard var I närheten? 🤔

**Comment by tobbep1997** [comment]
Jag fixade precis att particle passet inte skriver över alla ljus i guard vis passet

**Comment by tobbep1997** [comment]
Fixed
