### ISSUE TITLE
Ai fucked error msg

### ISSUE THREAD

**Issue by TheFlyingPandaa** [tobbep1997/RipTag#68]
`D3D11 WARNING: ID3D11DeviceContext::Draw: The size of the Constant Buffer at slot 0 of the Pixel Shader unit is too small (48 bytes provided, 400 bytes, at least, expected). This is OK, as out-of-bounds reads are defined to return 0. It is also possible the developer knows the missing data will not be used anyway. This is only a problem if the developer actually intended to bind a sufficiently large Constant Buffer for what the shader expects.  [ EXECUTION WARNING #351: DEVICE_DRAW_CONSTANT_BUFFER_TOO_SMALL]`

`D3D11 WARNING: ID3D11DeviceContext::DrawInstanced: The size of the Constant Buffer at slot 0 of the Pixel Shader unit is too small (48 bytes provided, 400 bytes, at least, expected). This is OK, as out-of-bounds reads are defined to return 0. It is also possible the developer knows the missing data will not be used anyway. This is only a problem if the developer actually intended to bind a sufficiently large Constant Buffer for what the shader expects.  [ EXECUTION WARNING #351: DEVICE_DRAW_CONSTANT_BUFFER_TOO_SMALL]`

**Comment by tobbep1997** [comment]
Detta är på grund av att Particels skriver över slot 0 i pixel shadern.

Now Fixed.
