### ISSUE TITLE
Pressure plates

### ISSUE THREAD

**Issue by Guffti** [tobbep1997/RipTag#70]
Om man står två på samma pressure plate och en går av inaktiveras den

**Comment by maxtla** [comment]
Testa med senaste DEV. Jag kollar om RemotePlayer fortfarande befinner sig i PressurePlate's boundingbox. 
Jag använder DirectX BB för detta, om de inte är identiska med Bounce's BB så kommer det nog inte bete sig som förväntat. Annars bör det ju funka.

**Comment by Guffti** [comment]
Fortfarande likadant

**Comment by maxtla** [comment]
Jag använder Bounce AABB nu istället, testa igen.

**Comment by Guffti** [comment]
Fortfarande likadant

**Comment by Guffti** [comment]
Jag ställer mig på pressure platen.
->Den sätts till "True".
Min medspelare ställer sig på samma pressure plate. 
Meddelande skickas om att sätta den till "True".
->Den sätts till "True" igen, ingenting ändras.
Min medspelare går ifrån pressure platen.
Meddelande skickas om att sätta den till "False".
*Här behövs en koll om jag fortfarande står kvar på pressure platen*
->Den sätts till "False". 

Min teori om vad som går fel. Kan det stämma?

**Comment by maxtla** [comment]
Det jag försöker göra är att kolla om min RemotePLayer befinner sig i Objektets boundingbox, ifall det är så så ska jag inte ändra objektets state och inget paket behövs skickas. Det är bättre att lösa det så att paket inte ens skickas.

**Comment by maxtla** [comment]
Jag misstänker att DX::g_remotePlayer alltid är nullptr? men har ingen möjlighet att verifiera det hemma.

**Comment by maxtla** [comment]
Funkar bra om spelaren står kvar centralt på plattan, bounding boxen vi kollar med har något mindre scaling än hur objektet ser ut i världen, but it wörks so it ok.
