### ISSUE TITLE
Vi har constant buffer problem i dev... Ljusen slutar fungera och DirectX skriker

### ISSUE THREAD

**Issue by nipplesticks** [tobbep1997/RipTag#71]

**Comment by tobbep1997** [comment]
Fixat i #68 
Har också en plan för att fixa :

`D3D11 WARNING: ID3D11DeviceContext::OMSetRenderTargets: Resource being set to OM DepthStencil is still bound on input! [ STATE_SETTING WARNING #9: DEVICE_OMSETRENDERTARGETS_HAZARD]`

`D3D11 WARNING: ID3D11DeviceContext::OMSetRenderTargets[AndUnorderedAccessViews]: Forcing PS shader resource slot 10 to NULL. [ STATE_SETTING WARNING #7: DEVICE_PSSETSHADERRESOURCES_HAZARD]`

Det har med Visability passet när det finns mer än en guard som körs
