### ISSUE TITLE
SmokeBomb flickrar 

### ISSUE THREAD

**Issue by viggeron1337** [tobbep1997/RipTag#78]
SmokeBomben flickrar (Har endast sett detta problemet på nivå 2). Den kan ses från visa vinklar men inte andra när den väl börjat flickra.

**Comment by RavioliFinoli** [comment]
Kanske kan vara för att alla quads spawnar på samma ställa så det blir Z-fighting, isf kan det hjälpa att bara ha en random liten offset när den spawnar

**Comment by TheFlyingPandaa** [comment]
De flickar inte.
De blev helt bort cullade.
Fixat nu
