### ISSUE TITLE
MemoryLeak

### ISSUE THREAD

**Issue by tobbep1997** [tobbep1997/RipTag#9]
Minnesläcka i Room.h

När man startar spelet och går tillbaka till menyn är det lungt.
Men andra gången så kommer det en minnesläcka och tredje gången kommer det två.

**Comment by TheFlyingPandaa** [comment]
Ljudet är det som lever kvar mellan menyn och spelet.
Kan det vara så att den startar en ny instans av ljudet.

så du har 2 stycken i playstate
Vet inte riktigt hur det funkar, så tar det på tisdag

**Comment by TheFlyingPandaa** [comment]
Det ÄR INTE collision boxes @Guffti

Så det är bara att fortsätta leta 😄🔫

**Comment by TheFlyingPandaa** [comment]
Det är inte levelHandlern

**Comment by tobbep1997** [comment]
Finaly found it... It was the CameraHandler
